apiVersion: v1
kind: Namespace
metadata:
  name: saasbench-baserow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baserow
  namespace: saasbench-baserow
  labels: &id001
    app: baserow
spec:
  replicas: 1
  selector:
    matchLabels: *id001
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: baserow
        image: mw-baserow:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 6806
        env:
        - name: BASEROW_PUBLIC_URL
          value: http://localhost
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 60
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: baserow
  namespace: saasbench-baserow
  labels: &id001
    app: baserow
spec:
  type: NodePort
  selector: *id001
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30103
