apiVersion: v1
kind: Namespace
metadata:
  name: saasbench-farmos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: farmos
  namespace: saasbench-farmos
  labels: &id001
    app: farmos
spec:
  replicas: 1
  selector:
    matchLabels: *id001
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: farmos
        image: mw-farmos:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 80
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 60
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: farmos
  namespace: saasbench-farmos
  labels: &id001
    app: farmos
spec:
  type: NodePort
  selector: *id001
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30116
