apiVersion: v1
kind: Namespace
metadata:
  name: saasbench-openproject
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openproject
  namespace: saasbench-openproject
  labels: &id001
    app: openproject
spec:
  replicas: 1
  selector:
    matchLabels: *id001
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: openproject
        image: mw-openproject:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 80
        env:
        - name: OPENPROJECT_HOST__NAME
          value: s0-openproject.saasbench.localhost
        - name: OPENPROJECT_ADDITIONAL_HOSTS
          value: localhost,127.0.0.1,s0-openproject.saasbench.localhost
        - name: OPENPROJECT_HTTPS
          value: 'false'
        - name: SECRET_KEY_BASE
          value: secret
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 60
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: openproject
  namespace: saasbench-openproject
  labels: &id001
    app: openproject
spec:
  type: NodePort
  selector: *id001
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30101
