apiVersion: v1
kind: Namespace
metadata:
  name: saasbench-opnform
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opnform
  namespace: saasbench-opnform
  labels: &id001
    app: opnform
spec:
  replicas: 1
  selector:
    matchLabels: *id001
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: opnform
        image: mw-opnform:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8080
        env:
        - name: APP_URL
          value: http://localhost
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 60
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: opnform
  namespace: saasbench-opnform
  labels: &id001
    app: opnform
spec:
  type: NodePort
  selector: *id001
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30109
