apiVersion: v1
kind: Namespace
metadata:
  name: saasbench-twenty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twenty
  namespace: saasbench-twenty
  labels: &id001
    app: twenty
spec:
  replicas: 1
  selector:
    matchLabels: *id001
  template:
    metadata:
      labels: *id001
    spec:
      containers:
      - name: twenty
        image: mw-twenty:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: SERVER_URL
          value: http://localhost
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 60
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 180
          periodSeconds: 10
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: twenty
  namespace: saasbench-twenty
  labels: &id001
    app: twenty
spec:
  type: NodePort
  selector: *id001
  ports:
  - name: http
    port: 80
    targetPort: http
    nodePort: 30104
